name: Build Node Application
on: push
jobs:
    build-jobs:
        name: Build Node
        runs-on: ubuntu-latest
        container: node:14
        steps:
            - run: node --version
              name: Node Version
            - run: npm -- version
              name: NPM Version
            - run: npm i --save moment
              name: Install NPM
            - run: node app.js
              name: Run Application
              
